kind: Service
apiVersion: v1
metadata:
    name: juice-shop
    namespace: chkpnms
spec:
    type: ClusterIP
    selector:
        app: juice-shop
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 3000